### PR TITLE
fix: etcd version(#2)

### LINKED ISSUE #2: go get error
E:\source\golang_demo\src\casbin.demo>go get github.com/sebastianliu/etcd-adapter
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/casbin/casbin/model
go: finding module for package github.com/casbin/casbin/persist
go: found github.com/casbin/casbin/model in github.com/casbin/casbin v1.9.1
go: found github.com/casbin/casbin/persist in github.com/casbin/casbin v1.9.1
go: found github.com/coreos/etcd/clientv3 in github.com/coreos/etcd v3.3.25+incompatible
go: finding module for package google.golang.org/grpc/metadata
go: finding module for package google.golang.org/grpc/keepalive
go: finding module for package go.uber.org/zap
go: finding module for package google.golang.org/grpc/grpclog
go: finding module for package google.golang.org/grpc/credentials
go: finding module for package google.golang.org/grpc
go: finding module for package go.uber.org/zap/zapcore
go: finding module for package github.com/google/uuid
go: finding module for package google.golang.org/grpc/status
go: finding module for package github.com/coreos/go-systemd/journal
go: finding module for package google.golang.org/grpc/resolver
go: finding module for package github.com/coreos/go-semver/semver
go: finding module for package github.com/coreos/pkg/capnslog
go: finding module for package github.com/golang/protobuf/proto
go: finding module for package google.golang.org/grpc/balancer
go: finding module for package google.golang.org/grpc/codes
go: finding module for package google.golang.org/grpc/resolver/passthrough
go: finding module for package github.com/gogo/protobuf/gogoproto
go: finding module for package google.golang.org/grpc/connectivity
go: finding module for package google.golang.org/grpc/resolver/dns
go: finding module for package google.golang.org/genproto/googleapis/api/annotations
go: found github.com/coreos/pkg/capnslog in github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: found github.com/google/uuid in github.com/google/uuid v1.1.2
go: found go.uber.org/zap in go.uber.org/zap v1.16.0
go: found google.golang.org/grpc in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/codes in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/credentials in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/grpclog in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/keepalive in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/metadata in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/status in google.golang.org/grpc v1.34.0
go: found github.com/gogo/protobuf/gogoproto in github.com/gogo/protobuf v1.3.1
go: found github.com/golang/protobuf/proto in github.com/golang/protobuf v1.4.3
go: found google.golang.org/grpc/balancer in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/connectivity in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/resolver in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/resolver/dns in google.golang.org/grpc v1.34.0
go: found google.golang.org/grpc/resolver/passthrough in google.golang.org/grpc v1.34.0
go: found go.uber.org/zap/zapcore in go.uber.org/zap v1.16.0
go: found google.golang.org/genproto/googleapis/api/annotations in google.golang.org/genproto v0.0.0-20201214200347-8c77b98c765d
go: found github.com/coreos/go-systemd/journal in github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf
go: found github.com/coreos/go-semver/semver in github.com/coreos/go-semver v0.3.0
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
..\..\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
..\..\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
..\..\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
..\..\pkg\mod\github.com\coreos\etcd@v3.3.25+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions

### PR DESCRIPTION
**Pull request by kilosonc**
Signed-off-by: closetool <c299999999@qq.com>

fix: #2

### CODE REVIEW

**Comment by kilosonc** [comment]
@sebastianliu plz review

**Comment by hsluoyz** [comment]
@gzhsnail please review.

**Comment by hsluoyz** [comment]
Hi @sebastianliu can you review this PR?

**Comment by sebastianliu** [comment]
@kilosonc @hsluoyz Sorry for the late review, I will review this ASAP

**Comment by hsluoyz** [comment]
@sebastianliu thanks!

**Comment by hsluoyz** [comment]
@sebastianliu thanks for merging! Can you make a new release so people can use it? (git tag and GitHub Release)

image

**Comment by sebastianliu** [comment]
> 

Done

**Pull request merged**
